package com.e.common.db.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table CACHES.
 */
public class Caches implements java.io.Serializable {

    private Long _id;
    private String content;
    private String type;
    private Long lastRefreshTimestamp;

    public Caches() {
    }

    public Caches(Long _id) {
        this._id = _id;
    }

    public Caches(Long _id, String content, String type, Long lastRefreshTimestamp) {
        this._id = _id;
        this.content = content;
        this.type = type;
        this.lastRefreshTimestamp = lastRefreshTimestamp;
    }

    public Long get_id() {
        return _id;
    }

    public void set_id(Long _id) {
        this._id = _id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Long getLastRefreshTimestamp() {
        return lastRefreshTimestamp;
    }

    public void setLastRefreshTimestamp(Long lastRefreshTimestamp) {
        this.lastRefreshTimestamp = lastRefreshTimestamp;
    }

}
